SET SERVEROUTPUT ON;

VARIABLE B_PERIODO NUMBER;
EXEC :B_PERIODO :=2019;

DECLARE
    CURSOR CUR_ASESORIA IS
    SELECT
        NUMRUN_PROF,
        COD_EMPRESA,
        SUM(HONORARIO) as HONORARIO,
        INICIO_ASESORIA,
        FIN_ASESORIA
        FROM ASESORIA
        WHERE EXTRACT (YEAR FROM FIN_ASESORIA) = :B_PERIODO
        GROUP BY NUMRUN_PROF, COD_EMPRESA, INICIO_ASESORIA, FIN_ASESORIA
        ORDER BY NUMRUN_PROF, FIN_ASESORIA ASC;
        
    CURSOR CUR_EMPRESA (P_ID_EMPRESA NUMBER) IS
    SELECT *
        FROM EMPRESA
        WHERE COD_EMPRESA = P_ID_EMPRESA;

V_EMPRESA_S SECTOR%ROWTYPE;
V_EMPRESA_C COMUNA%ROWTYPE;
V_NOMBRE_EMPRESA VARCHAR(30);
V_NOMBRE_SECTOR SECTOR.NOMBRE_SECTOR%TYPE;
V_NOMBRE_COMUNA COMUNA.NOM_COMUNA%TYPE;
V_CANTIDAD_DIAS_ASESORIA NUMBER;
V_HONORARIOS_POR_DIA NUMBER;
V_MENSAJE_DE_ERROR VARCHAR(100);
V_CODIGO_DE_ERROR VARCHAR(100);
BEGIN

    EXECUTE IMMEDIATE 'TRUNCATE TABLE RESUMEN_ASESORIA';
    EXECUTE IMMEDIATE 'TRUNCATE TABLE ERRORES_PROCESO';
    
    FOR X IN CUR_ASESORIA LOOP
    
        FOR Y IN CUR_EMPRESA (X.COD_EMPRESA) LOOP
        
            SELECT
                S.NOMBRE_SECTOR INTO V_NOMBRE_SECTOR
            FROM SECTOR S
            WHERE S.COD_SECTOR = Y.COD_SECTOR;
            
            SELECT
                C.NOM_COMUNA INTO V_NOMBRE_COMUNA
            FROM COMUNA C
            WHERE C.COD_COMUNA = Y.COD_COMUNA;
            
            V_NOMBRE_EMPRESA := Y.NOMBRE_EMPRESA;
            V_CANTIDAD_DIAS_ASESORIA := X.FIN_ASESORIA - X.INICIO_ASESORIA;
            V_HONORARIOS_POR_DIA := ROUND(X.HONORARIO/V_CANTIDAD_DIAS_ASESORIA);
            
        END LOOP;
        
        INSERT INTO RESUMEN_ASESORIA
            VALUES(X.NUMRUN_PROF, V_NOMBRE_EMPRESA, V_NOMBRE_SECTOR, V_NOMBRE_COMUNA,
                   X.INICIO_ASESORIA, X.FIN_ASESORIA, V_CANTIDAD_DIAS_ASESORIA, X.HONORARIO,
                   V_HONORARIOS_POR_DIA);
        
        
        DBMS_OUTPUT.PUT_LINE(X.NUMRUN_PROF||' '||V_NOMBRE_EMPRESA||' '||V_NOMBRE_SECTOR||
            ' '||V_NOMBRE_COMUNA||' '||X.INICIO_ASESORIA||' '||X.FIN_ASESORIA||' '|| V_CANTIDAD_DIAS_ASESORIA||
            ' '||X.HONORARIO||' '||V_HONORARIOS_POR_DIA);
            
    END LOOP;
    
    EXCEPTION
   WHEN OTHERS THEN 
   V_MENSAJE_DE_ERROR:=SQLERRM; 
   V_CODIGO_DE_ERROR:=SQLCODE; 
   INSERT INTO ERRORES_PROCESO
   VALUES(sq_error.NEXTVAL, V_CODIGO_DE_ERROR, V_MENSAJE_DE_ERROR);   
END;